### ISSUE TITLE
Programmatically generate invoices for workshop ticket orders

### ISSUE THREAD

**Issue by Oddant1** [qiime2/workshops#123]
**Improvement Description**
Generate a meaningful invoice/receipt to be attached to the emails already being sent to people who purchase tickets to QIIME 2 workshops.

**Current Behavior**
Purchasers receive an invoice attached to an email from the third party service that handles the transactions. These are frequently lost or caught in spam filters resulting in the need for the admin team to manually create an invoice for the workshop attendee to be able to receive a reimbursement from their institute.

**Proposed Behavior**
Automatically create something resembling these invoices to be attached to the initial confirmation emails we send to attendees.

**Questions**
1. What do we want the .pdf to look like?
2. How long do we want this .pdf to live on the server?
3. How do we want to integrate this .pdf creation into the current ordering process? It shouldn't be too hard to just automatically create the .pdf on the current submit page right before we email it off to them.

**References**
1. https://workshops.qiime2.org/

**Comment by Oddant1** [comment]
I emailed Alyssa Barrett at HR about how she currently goes about creating these files, and she emailed me a .xlsx file for an invoice she produced for the workshop in New York on June 3rd/4th. This got me thinking, would it perhaps make more sense to create a .xlsx template that we can modify to create invoices? Then we save the completed invoice to a .pdf before attaching it to the email? There is a module called XlsxWriter that should, at a glance, let us do something like this. With a .pdf, the entire file will have to be programmatically generate each time we want an invoice due to the lack of real ability to edit a .pdf. With a .xlsx file (or any similar format really) we would just need to fill in the template (which may result in some things being moved around depending on what their invoice needs). I'm not sure if this would necessarily be better or easier, but it's a thought.

**Comment by Oddant1** [comment]
In fact, maybe this shouldn't be done as a .pdf using reportlab at all, maybe it makes more sense to make this as a .html file then convert that to a .pdf.

**Comment by thermokarst** [comment]
> This got me thinking, would it perhaps make more sense to create a .xlsx template that we can modify to create invoices? Then we save the completed invoice to a .pdf before attaching it to the email?

I like where you're going with this --- luckily that is what the database is for! 

> With a .pdf, the entire file will have to be programmatically generate each time we want an invoice due to the lack of real ability to edit a .pdf.

That's fine, no need to edit the PDF. The PDF is only created _after_ all the info is collated.

> In fact, maybe this shouldn't be done as a .pdf using reportlab at all, maybe it makes more sense to make this as a .html file then convert that to a .pdf.

That could work, just another strategy for making a PDF - it all works for me!

> What do we want the .pdf to look like?

How about the physical printout I gave you last week? I think that has been working well, and can get us set up for any other edits.

> How long do we want this .pdf to live on the server?

Probably forever --- but, on S3, not the Django webserver. I can show you how we can do this next week when I am around.

> How do we want to integrate this .pdf creation into the current ordering process? It shouldn't be too hard to just automatically create the .pdf on the current submit page right before we email it off to them.

There is a [callback endpoint](https://github.com/qiime2/workshops/blob/ae5daf816448a6db6d08a53a4f1cd11d7bd26d56/workshops/payments/views.py#L280-L317) that gets triggered when NAU receives payment, this is a good place to start.

**Comment by Oddant1** [comment]
@thermokarst :  
>There is a [callback endpoint](https://github.com/qiime2/workshops/blob/ae5daf816448a6db6d08a53a4f1cd11d7bd26d56/workshops/payments/views.py#L280-L317) that gets triggered when NAU receives payment, this is a good place to start.
I looked at this, and I don't think I have a way to test this right now do I? Unless there is a way for me to spoof NAU receiving payment locally?

**Comment by thermokarst** [comment]
You can simulate the NAU payment receipt by manually POSTing to your development server. `$ORDER_TRANSACTION_ID`, `$ORDER_TOTAL`, and `$ORDER_DATETIME` are all specific to the order in question. You can use any tool for this, I just happen to like `curl`:

```bash
curl -d "unique_id=$ORDER_TRANSACTION_ID&amount=$ORDER_TOTAL&date_time=$ORDER_DATETIME" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -X POST http://localhost:8000/confirm/
```

**Comment by Oddant1** [comment]
@thermokarst awesome, thank you

**Comment by Oddant1** [comment]
@thermokarst this is where I'm at with the document right now.
[Invoice.pdf](https://github.com/qiime2/workshops/files/3370077/Invoice.pdf)

**Comment by thermokarst** [comment]
This looks awesome @Oddant1! Want to open a `Draft PR` with your work to date? We can continue detailed discussion there. Thanks!

**Comment by Oddant1** [comment]
@thermokarst I'll do that before I leave today with the latest version of the document. It's currently displaying on the `submit` view because I couldn't make the POST with curl work in any way I could make sense of. I'll talk to you about that in person next chance I get.

**Comment by Oddant1** [comment]
@thermokarst new example invoice generated by the code in the inital PR #124 
[Invoice1.pdf](https://github.com/qiime2/workshops/files/3370674/Invoice1.pdf)

**Comment by Oddant1** [comment]
@thermokarst made some of the changes we discussed
[invoice2.pdf](https://github.com/qiime2/workshops/files/3374625/invoice2.pdf)
